# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  schedule:
    - cron: "1 16 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: curl 'http://bbs.weibufengge.com/plugin.php?id=dsu_paulsign:sign&operation=qiandao&infloat=1&inajax=1' -H 'Proxy-Connection:keep-alive' -H 'Cache-Control:max-age=0'   -H 'Origin:http://bbs.weibufengge.com'   -H 'Upgrade-Insecure-Requests:1'   -H 'DNT:1'   -H 'Content-Type:application/x-www-form-urlencoded'   -H 'User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36'   -H 'Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'   -H 'Referer:http://bbs.weibufengge.com/plugin.php?id=dsu_paulsign:sign'   -H 'Accept-Language:zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7,ja;q=0.6,zh-TW;q=0.5,uk;q=0.4,ko;q=0.3,sv;q=0.2'   -H 'Cookie:PSPH_2132_saltkey=fbQWBWSO; PSPH_2132_lastvisit=1587885449; PSPH_2132_auth=b6adj76khvRq%2B%2B%2B%2Fe7tZljQBFyQkL5ZX%2Bj1QdZXZ3Z6lkv3jmPVBFZ5B0TcfjDSwV7Z1Cp1WqWkpJmnsFSK1B8tz9Q; PSPH_2132_lastcheckfeed=11333%7C1587889055; PSPH_2132_connect_is_bind=0; PSPH_2132_nofavfid=1; PSPH_2132_smile=325D1; PHPSESSID=isggbfku7ui46ucukm6m7lu647; PSPH_2132_st_p=11333%7C1590395763%7C2b133be539bf591cbb9bcc816b14d82b; PSPH_2132_visitedfid=73D7D4D51D12; PSPH_2132_viewid=tid_246822; PSPH_2132_onlineusernum=109; PSPH_2132_ulastactivity=8795NKs%2FO9T%2F5iSSlEfVyNL0tfR618RMMToCM6Sks2%2BrJvveo44r; PSPH_2132_sendmail=1; PSPH_2132_sid=RGpJJ6; PSPH_2132_lip=218.80.1.99%2C1590480433; PSPH_2132_lastact=1590480434%09misc.php%09patch'   --data 'formhash=0a0b28a4&qdxq=kx&qdmode=1&todaysay=%B4%F2%BF%A8%B4%F2%BF%A8&fastreply=0'   --compressed   --insecure
