# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  schedule:
    - cron: "1 8 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Sign In 
      run: curl 'http://bbs.weibufengge.com/plugin.php?id=dsu_paulsign:sign&operation=qiandao&infloat=1&inajax=1' -H 'Proxy-Connection:keep-alive' -H 'Cache-Control:max-age=0' -H 'Origin:http://bbs.weibufengge.com' -H 'Upgrade-Insecure-Requests:1' -H 'DNT:1' -H 'Content-Type:application/x-www-form-urlencoded' -H 'User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36' -H 'Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' -H 'Referer:http://bbs.weibufengge.com/plugin.php?id=dsu_paulsign:sign' -H 'Accept-Language:zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7,ja;q=0.6,zh-TW;q=0.5,uk;q=0.4,ko;q=0.3,sv;q=0.2' -H 'Cookie:PHPSESSID=dje8f0n2v39r7s1heb175bp3l4; PSPH_2132_saltkey=o0TKvZsv; PSPH_2132_lastvisit=1598697003; PSPH_2132_seccode=107.5f21f63a0d3bc745fa; PSPH_2132_auth=ca1aFo2Hi499I9%2FbdPdx6FZgQMEl4CYWFQeGBV0jkSeJ%2Bef1JNzxFvnkHFfqrWaGJyfisHHiQ9TWAbbExz%2Fz6idXNg; PSPH_2132_lastcheckfeed=11333%7C1598700614; PSPH_2132_connect_is_bind=0; PSPH_2132_visitedfid=4; PSPH_2132_st_t=11333%7C1598700617%7Cb4f393beb03afc50108315e04537bb85; PSPH_2132_forum_lastvisit=D_4_1598700617; PSPH_2132_viewid=tid_247205; PSPH_2132_smile=325D1; PSPH_2132_clearUserdata=forum; PSPH_2132_connect_not_sync_t=1; PSPH_2132_st_p=11333%7C1598700650%7Ce74d4306bf8d170c6154117e1a3f4040; PSPH_2132_nofavfid=1; PSPH_2132_sid=YJ6Ar3; PSPH_2132_lip=40.121.82.207%2C1598921394; PSPH_2132_onlineusernum=278; PSPH_2132_ulastactivity=0670GY0uFOV1XvT9yviyh1S%2FPH3W6FciPt95MUMXx%2FPTEpOoCtnN; PSPH_2132_sendmail=1; PSPH_2132_taskdoing_11333=1; PSPH_2132_lastact=1598939496%09misc.php%09patch' --data-raw 'formhash=88aa95b8&qdxq=kx&qdmode=1&todaysay=We+Will+We+Will+Rock+You&fastreply=0' --compressed --insecure
