# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  schedule:
    - cron: "1 16 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: curl 'http://bbs.weibufengge.com/plugin.php?id=dsu_paulsign:sign&operation=qiandao&infloat=1&inajax=1' -H 'Proxy-Connection:keep-alive' -H 'Cache-Control:max-age=0'  -H 'Origin:http://bbs.weibufengge.com'   -H 'Upgrade-Insecure-Requests:1'   -H 'DNT:1'   -H 'Content-Type:application/x-www-form-urlencoded'   -H 'User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36'   -H 'Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'   -H 'Referer:http://bbs.weibufengge.com/plugin.php?id=dsu_paulsign:sign'   -H 'Accept-Language:zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7,ja;q=0.6,zh-TW;q=0.5,uk;q=0.4,ko;q=0.3,sv;q=0.2'   -H 'Cookie:PHPSESSID=5qnmvvm97gbu8e2l7p8lq4vi24; PSPH_2132_saltkey=X4Evvm8R; PSPH_2132_lastvisit=1592958470; PSPH_2132_seccode=26.edea7f57438454d0e6; PSPH_2132_auth=5c52%2BizSP2u5QFH4R95%2FvWlirx5tTGS35sbSTDQj%2B1RO8o38sz0GyQYn09V062t2CU2rzYvjzRlhvHVGXyC1TeU0HA; PSPH_2132_lastcheckfeed=11333%7C1592962076; PSPH_2132_connect_is_bind=0; PSPH_2132_nofavfid=1; PSPH_2132_ulastactivity=e7d0hrUIklDtBRJ75bwF4MEjJiJSi1YW533GQrY3rtBU8bvZMolv; PSPH_2132_sendmail=1; PSPH_2132_checkpm=1; PSPH_2132_sid=Okgzdz; PSPH_2132_lip=218.80.1.63%2C1593336966; PSPH_2132_lastact=1593336966%09misc.php%09patch'  --data-raw 'formhash=d7cfdc65&qdxq=kx&qdmode=1&todaysay=%B9%A7%CF%B2%C2%DB%CC%B3%BB%D6%B8%B4%A1%A3&fastreply=0'  --compressed   --insecure
