# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  schedule:
    - cron: "1 8 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Sign In 
      run: curl 'http://bbs.weibufengge.com/plugin.php?id=dsu_paulsign:sign&operation=qiandao&infloat=1&sign_as=1&inajax=1'   -H 'Connection: keep-alive'   -H 'Cache-Control: max-age=0'   -H 'Origin: http://bbs.weibufengge.com'   -H 'Upgrade-Insecure-Requests: 1'   -H 'DNT: 1'   -H 'Content-Type: application/x-www-form-urlencoded'   -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36 Edg/85.0.564.51'   -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'   -H 'Referer: http://bbs.weibufengge.com/'   -H 'Accept-Language: en-US,en;q=0.9,zh-CN;q=0.8,zh-TW;q=0.7,zh;q=0.6'   -H 'Cookie: PSPH_2132_saltkey=MPW4tGmg; PSPH_2132_lastvisit=1600248665; PSPH_2132_auth=52a4ZPcn7Uw795hfF9cjWcKHaFrG67oulS%2FznUP49HUTd3pZuo8HyRUrAoyzmksqYxlxfDpxWHTkxEh8jA7CcQ%2FJEA; PSPH_2132_lastcheckfeed=11333%7C1600252271; PSPH_2132_connect_is_bind=0; PSPH_2132_nofavfid=1; PSPH_2132_smile=325D1; PSPH_2132_forum_lastvisit=D_4_1600507683; PHPSESSID=75os1p4nehq570h0hde2kdakb0; PSPH_2132_st_p=11333%7C1600788629%7C75a0b39957040e7c33259bfcb0898e0e; PSPH_2132_visitedfid=73D4; PSPH_2132_viewid=tid_247303; PSPH_2132_sid=u1OQnN; PSPH_2132_lip=23.99.151.240%2C1600848815; PSPH_2132_onlineusernum=374; PSPH_2132_ulastactivity=1be5jOysT53sYEZney%2BZmHs%2BJy1fKa0demQXCHpsq4nePHNGNywN; PSPH_2132_sendmail=1; PSPH_2132_lastact=1600858523%09plugin.php%09'   --data-raw 'formhash=5d1a657d&qdxq=kx&qdmode=1&todaysay=%B9%A7%CF%B2%C2%DB%CC%B3%BB%D6%B8%B4%A1%A3&fastreply=0'   --compressed   --insecure
